#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULES_DIR="${BASE_DIR}/.dotbot"

cd "${BASE_DIR}"

for module in "${MODULES_DIR}"/*; do
    git -C "${module}" submodule sync --quiet --recursive
    git submodule update --init --recursive "${module}"
done

"${MODULES_DIR}/dotbot/bin/dotbot" -d "${BASE_DIR}" -c install.conf.yaml \
    -p "${MODULES_DIR}/dotbot-ifplatform/ifplatform.py" \
    -p "${MODULES_DIR}/dotbot-includes/includes.py" \
    -p "${MODULES_DIR}/dotbot-brew/brew.py"
