- shell:
    - description: Add Docker's official GPG key
      command: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
          sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
    - description: Add Docker repository to Apt sources
      command: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
    - description: Install Docker with version found in versions.lock
      command: |
        sudo apt-get install -y \
          docker-ce=${DOCKER_VERSION} \
          docker-ce-cli=${DOCKER_VERSION} \
          containerd.io docker-buildx-plugin docker-compose-plugin
    - description: Run Docker test container
      command: sudo service docker start && sudo docker run --rm hello-world
    - description: Add current user to Docker group for non-root usage
      command: sudo groupadd -f docker && sudo usermod -aG docker $USER
